# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/mork/Documents/Winter2025/C++/comp-3400-project

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/mork/Documents/Winter2025/C++/comp-3400-project

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mork/Documents/Winter2025/C++/comp-3400-project/CMakeFiles /home/mork/Documents/Winter2025/C++/comp-3400-project//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mork/Documents/Winter2025/C++/comp-3400-project/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named hospital_system

# Build rule for target.
hospital_system: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hospital_system
.PHONY : hospital_system

# fast build rule for target.
hospital_system/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hospital_system.dir/build.make CMakeFiles/hospital_system.dir/build
.PHONY : hospital_system/fast

src/Date.o: src/Date.cpp.o
.PHONY : src/Date.o

# target to build an object file
src/Date.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hospital_system.dir/build.make CMakeFiles/hospital_system.dir/src/Date.cpp.o
.PHONY : src/Date.cpp.o

src/Date.i: src/Date.cpp.i
.PHONY : src/Date.i

# target to preprocess a source file
src/Date.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hospital_system.dir/build.make CMakeFiles/hospital_system.dir/src/Date.cpp.i
.PHONY : src/Date.cpp.i

src/Date.s: src/Date.cpp.s
.PHONY : src/Date.s

# target to generate assembly for a file
src/Date.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hospital_system.dir/build.make CMakeFiles/hospital_system.dir/src/Date.cpp.s
.PHONY : src/Date.cpp.s

src/Doctor.o: src/Doctor.cpp.o
.PHONY : src/Doctor.o

# target to build an object file
src/Doctor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hospital_system.dir/build.make CMakeFiles/hospital_system.dir/src/Doctor.cpp.o
.PHONY : src/Doctor.cpp.o

src/Doctor.i: src/Doctor.cpp.i
.PHONY : src/Doctor.i

# target to preprocess a source file
src/Doctor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hospital_system.dir/build.make CMakeFiles/hospital_system.dir/src/Doctor.cpp.i
.PHONY : src/Doctor.cpp.i

src/Doctor.s: src/Doctor.cpp.s
.PHONY : src/Doctor.s

# target to generate assembly for a file
src/Doctor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hospital_system.dir/build.make CMakeFiles/hospital_system.dir/src/Doctor.cpp.s
.PHONY : src/Doctor.cpp.s

src/Employee.o: src/Employee.cpp.o
.PHONY : src/Employee.o

# target to build an object file
src/Employee.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hospital_system.dir/build.make CMakeFiles/hospital_system.dir/src/Employee.cpp.o
.PHONY : src/Employee.cpp.o

src/Employee.i: src/Employee.cpp.i
.PHONY : src/Employee.i

# target to preprocess a source file
src/Employee.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hospital_system.dir/build.make CMakeFiles/hospital_system.dir/src/Employee.cpp.i
.PHONY : src/Employee.cpp.i

src/Employee.s: src/Employee.cpp.s
.PHONY : src/Employee.s

# target to generate assembly for a file
src/Employee.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hospital_system.dir/build.make CMakeFiles/hospital_system.dir/src/Employee.cpp.s
.PHONY : src/Employee.cpp.s

src/Hospital.o: src/Hospital.cpp.o
.PHONY : src/Hospital.o

# target to build an object file
src/Hospital.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hospital_system.dir/build.make CMakeFiles/hospital_system.dir/src/Hospital.cpp.o
.PHONY : src/Hospital.cpp.o

src/Hospital.i: src/Hospital.cpp.i
.PHONY : src/Hospital.i

# target to preprocess a source file
src/Hospital.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hospital_system.dir/build.make CMakeFiles/hospital_system.dir/src/Hospital.cpp.i
.PHONY : src/Hospital.cpp.i

src/Hospital.s: src/Hospital.cpp.s
.PHONY : src/Hospital.s

# target to generate assembly for a file
src/Hospital.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hospital_system.dir/build.make CMakeFiles/hospital_system.dir/src/Hospital.cpp.s
.PHONY : src/Hospital.cpp.s

src/Main.o: src/Main.cpp.o
.PHONY : src/Main.o

# target to build an object file
src/Main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hospital_system.dir/build.make CMakeFiles/hospital_system.dir/src/Main.cpp.o
.PHONY : src/Main.cpp.o

src/Main.i: src/Main.cpp.i
.PHONY : src/Main.i

# target to preprocess a source file
src/Main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hospital_system.dir/build.make CMakeFiles/hospital_system.dir/src/Main.cpp.i
.PHONY : src/Main.cpp.i

src/Main.s: src/Main.cpp.s
.PHONY : src/Main.s

# target to generate assembly for a file
src/Main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hospital_system.dir/build.make CMakeFiles/hospital_system.dir/src/Main.cpp.s
.PHONY : src/Main.cpp.s

src/Nurse.o: src/Nurse.cpp.o
.PHONY : src/Nurse.o

# target to build an object file
src/Nurse.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hospital_system.dir/build.make CMakeFiles/hospital_system.dir/src/Nurse.cpp.o
.PHONY : src/Nurse.cpp.o

src/Nurse.i: src/Nurse.cpp.i
.PHONY : src/Nurse.i

# target to preprocess a source file
src/Nurse.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hospital_system.dir/build.make CMakeFiles/hospital_system.dir/src/Nurse.cpp.i
.PHONY : src/Nurse.cpp.i

src/Nurse.s: src/Nurse.cpp.s
.PHONY : src/Nurse.s

# target to generate assembly for a file
src/Nurse.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hospital_system.dir/build.make CMakeFiles/hospital_system.dir/src/Nurse.cpp.s
.PHONY : src/Nurse.cpp.s

src/Patient.o: src/Patient.cpp.o
.PHONY : src/Patient.o

# target to build an object file
src/Patient.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hospital_system.dir/build.make CMakeFiles/hospital_system.dir/src/Patient.cpp.o
.PHONY : src/Patient.cpp.o

src/Patient.i: src/Patient.cpp.i
.PHONY : src/Patient.i

# target to preprocess a source file
src/Patient.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hospital_system.dir/build.make CMakeFiles/hospital_system.dir/src/Patient.cpp.i
.PHONY : src/Patient.cpp.i

src/Patient.s: src/Patient.cpp.s
.PHONY : src/Patient.s

# target to generate assembly for a file
src/Patient.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hospital_system.dir/build.make CMakeFiles/hospital_system.dir/src/Patient.cpp.s
.PHONY : src/Patient.cpp.s

src/Pharmacy.o: src/Pharmacy.cpp.o
.PHONY : src/Pharmacy.o

# target to build an object file
src/Pharmacy.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hospital_system.dir/build.make CMakeFiles/hospital_system.dir/src/Pharmacy.cpp.o
.PHONY : src/Pharmacy.cpp.o

src/Pharmacy.i: src/Pharmacy.cpp.i
.PHONY : src/Pharmacy.i

# target to preprocess a source file
src/Pharmacy.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hospital_system.dir/build.make CMakeFiles/hospital_system.dir/src/Pharmacy.cpp.i
.PHONY : src/Pharmacy.cpp.i

src/Pharmacy.s: src/Pharmacy.cpp.s
.PHONY : src/Pharmacy.s

# target to generate assembly for a file
src/Pharmacy.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hospital_system.dir/build.make CMakeFiles/hospital_system.dir/src/Pharmacy.cpp.s
.PHONY : src/Pharmacy.cpp.s

src/Setup.o: src/Setup.cpp.o
.PHONY : src/Setup.o

# target to build an object file
src/Setup.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hospital_system.dir/build.make CMakeFiles/hospital_system.dir/src/Setup.cpp.o
.PHONY : src/Setup.cpp.o

src/Setup.i: src/Setup.cpp.i
.PHONY : src/Setup.i

# target to preprocess a source file
src/Setup.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hospital_system.dir/build.make CMakeFiles/hospital_system.dir/src/Setup.cpp.i
.PHONY : src/Setup.cpp.i

src/Setup.s: src/Setup.cpp.s
.PHONY : src/Setup.s

# target to generate assembly for a file
src/Setup.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hospital_system.dir/build.make CMakeFiles/hospital_system.dir/src/Setup.cpp.s
.PHONY : src/Setup.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... hospital_system"
	@echo "... src/Date.o"
	@echo "... src/Date.i"
	@echo "... src/Date.s"
	@echo "... src/Doctor.o"
	@echo "... src/Doctor.i"
	@echo "... src/Doctor.s"
	@echo "... src/Employee.o"
	@echo "... src/Employee.i"
	@echo "... src/Employee.s"
	@echo "... src/Hospital.o"
	@echo "... src/Hospital.i"
	@echo "... src/Hospital.s"
	@echo "... src/Main.o"
	@echo "... src/Main.i"
	@echo "... src/Main.s"
	@echo "... src/Nurse.o"
	@echo "... src/Nurse.i"
	@echo "... src/Nurse.s"
	@echo "... src/Patient.o"
	@echo "... src/Patient.i"
	@echo "... src/Patient.s"
	@echo "... src/Pharmacy.o"
	@echo "... src/Pharmacy.i"
	@echo "... src/Pharmacy.s"
	@echo "... src/Setup.o"
	@echo "... src/Setup.i"
	@echo "... src/Setup.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

